/**
 * Generate the D1 migration for Better Auth's tables.
 *
 * This asks the *installed* better-auth for its migration plan rather than
 * going through a separately versioned CLI: a schema that lags the library by
 * even one column fails at runtime (a missing `account.issuer` is exactly how
 * this bill came due once already).
 *
 * Run with: npm run db:generate -w @mind-meld/worker
 */
import { DatabaseSync } from 'node:sqlite'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getMigrations } from 'better-auth/db/migration'

const here = dirname(fileURLToPath(import.meta.url))
const output = join(here, '..', 'migrations', '0001_auth.sql')

// The options that matter to the schema are the feature flags, not the
// credentials — keep these in step with src/auth.ts.
const options = {
  appName: 'Mind Meld',
  // An empty in-memory database means every table is reported as new, so the
  // output is a complete schema rather than a diff against someone's laptop.
  database: new DatabaseSync(':memory:'),
  emailAndPassword: { enabled: true, requireEmailVerification: true },
  emailVerification: { sendOnSignUp: true, autoSignInAfterVerification: true },
  socialProviders: {
    google: { clientId: 'schema-only', clientSecret: 'schema-only' },
  },
  session: { expiresIn: 60 * 60 * 24 * 60, updateAge: 60 * 60 * 24 },
}

const { compileMigrations } = await getMigrations(options)
const sql = await compileMigrations()

if (!sql.trim()) {
  console.error('better-auth reported no schema to create — refusing to write an empty migration')
  process.exit(1)
}

const header = `-- Generated by scripts/generate-schema.mjs from the installed better-auth.
-- Do not hand-edit: re-run \`npm run db:generate\` after upgrading better-auth,
-- then apply with \`npm run db:migrate:local\` / \`db:migrate:remote\`.

`

mkdirSync(dirname(output), { recursive: true })
writeFileSync(output, header + sql.trim() + '\n')
console.log(`wrote ${output}`)
